// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd6fbicV5PlsdOOYrH6N9_2RFiZ08tWOo',
    appId: '1:197461520997:web:2a1c5b06b6c7a616a70c8c',
    messagingSenderId: '197461520997',
    projectId: 'pickapick-2747d',
    authDomain: 'pickapick-2747d.firebaseapp.com',
    storageBucket: 'pickapick-2747d.firebasestorage.app',
    measurementId: 'G-7DZ2XDNENX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlY7aTHozZP2DtqAR8nlb8-GK9prBV744',
    appId: '1:197461520997:android:912852aa85a7b30ca70c8c',
    messagingSenderId: '197461520997',
    projectId: 'pickapick-2747d',
    storageBucket: 'pickapick-2747d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKnRhhNC8str_9Z8YJ7Sx9D9s9XVxyPjE',
    appId: '1:197461520997:ios:c0083128afd94359a70c8c',
    messagingSenderId: '197461520997',
    projectId: 'pickapick-2747d',
    storageBucket: 'pickapick-2747d.firebasestorage.app',
    iosBundleId: 'com.example.picklePick',
  );
}
